### PR TITLE
Syncing accepted oauth api scopes with documented options

### PR DESCRIPTION
**Pull request by awagneratzendesk**
This pull request addresses https://github.com/okta/terraform-provider-okta/issues/1493 and syncs the validScopes for oauth api scopes with the options available in the Okta documentation available [here](https://developer.okta.com/docs/api/oauth2/)

This was tested locally to validate that the additional scopes can be successfully applied to an okta_app_oauth_api_scope resource. 

Tests pass successfully and I don't think this requires any additional documentation updates.

### CODE REVIEW

**Comment by monde** [comment]
Thanks @awagneratzendesk I'd love to get rid of the provider validator that uses that resource, the API already does input validation. I think we are doing such in v4

**Review by monde — APPROVED** [review]
THanks @awagneratzendesk :shipit:

**Review by monde — CHANGES_REQUESTED** [review]
@awagneratzendesk 🤔 "tested locally to validate"

**Comment by awagneratzendesk** [comment]
@monde Sorry about that, was a copy/paste error from moving to my forked repo instead of the main one. Fixed now!

**Review by monde — APPROVED** [review]

**Pull request merged**
