### PR TITLE
Website: repair several incomplete page renames

### PR DESCRIPTION
**Pull request by nfagerlund**
These broken nav links are causing broken build errors on terraform.io. 

Once these fixes are merged, please also cherry-pick them to the stable-website branch, in order to fix the website without requiring another provider release. 

The second commit here assumes that the `okta_profile_mapping` resource **was in fact renamed to `okta_user_profile_mapping_source`.** If the resource's real name is actually still okta_profile_mapping, that commit should not be merged, and instead the page rename from cc2e27b4463691bac4a589f043aa3794aa668e9a should be reverted.

### CODE REVIEW

**Review by quantumew — APPROVED** [review]
Good catch, LGTM.

**Comment by nfagerlund** [comment]
It looks like I don't have merge access to the terraform-providers org anymore; I think the teams got rearranged. Could I get you to do the merge and cherry-pick? Thank you! 🌻 

Also, have you confirmed that the `okta_profile_mapping` resource doesn't have that name anymore?

**Comment by quantumew** [comment]
@nfagerlund Thanks for getting me to check that again. Both in fact exist, that is where my confusion was coming from. `okta_user_profile_mapping_source` is a data source, and `okta_profile_mapping` is a resource, so this in fact was meant to be `okta_profile_mapping`. Once that rename occurs I will be sure to approve and merge!

https://github.com/terraform-providers/terraform-provider-okta/blob/master/okta/resource_okta_profile_mapping.go
https://github.com/terraform-providers/terraform-provider-okta/blob/master/okta/data_source_okta_user_profile_mapping_source.go

**Comment by nfagerlund** [comment]
Okay, thank you for double-checking! 😅 I've replaced that commit with a different one that just reverts the mistaken rename.

**Comment by nfagerlund** [comment]
Ping! This is still causing noise due to failing site build tasks.

**Review by quantumew — APPROVED** [review]
LGTM!

**Comment by quantumew** [comment]
Looks like I no longer have write access. Pinging the new maintainers.

**Comment by noinarisak** [comment]
@quantumew I have the ability to merge the PR. Let me know and happily press the "Big Green" button. 😀

**Comment by quantumew** [comment]
@noinarisak Please do! Thanks!

**Comment by nfagerlund** [comment]
It looks like I've recovered my merge permissions (🎉 ), so since this is approved, I'm gonna do it. 👍🏼

**Comment by nfagerlund** [comment]
Also cherry-picked to stable-website so our builds will recover later today.

**Pull request merged**
