### PR TITLE
Fixed attribute statements setup for preconfigured apps

### LINKED ISSUE #415: attribute_statements always triggers a change in okta_app_saml when using preconfigured_app
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
❯ terraform -v
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/oktadeveloper/okta v3.10.1
```

### Affected Resource(s)

- okta_app_saml

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "preconfigured_app" {
  label                    = var.app_name
  preconfigured_app        = var.app_market_name
  app_settings_json        = jsonencode({"baseUrl"= var.app_base_url})

  attribute_statements {
    type         = "GROUP"
    name         = "group"
    filter_type  = "REGEX"
    filter_value = ".*"
  }

  // groups are assigned through okta_app_group_assignment resource
  lifecycle {
    ignore_changes = [groups]
  }
}
```

### Terraform Output

The above always produces the following diff in a plan/apply:
```
  # module.elevation_K8s_preconfigured_saml_apps["elevation-ci-sbx-usc1"].okta_app_saml.preconfigured_app will be updated in-place
  ~ resource "okta_app_saml" "preconfigured_app" {
        id                         = "0oab68hcz4iJtFkKt5d6"
        name                       = "jenkins"
        # (24 unchanged attributes hidden)

      + attribute_statements {
          + filter_type  = "REGEX"
          + filter_value = ".*"
          + name         = "group"
          + namespace    = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
          + type         = "GROUP"
        }
    }
```

### Expected Behavior

The resource should define the `attribute_statements` once and not show any diff unless the configuration was changed.

### Actual Behavior

Every plan produces the above diff.

### Steps to Reproduce

1. create an `okta_app_saml` with a `preconfigured_app` (we use `Jenkins`)
2. apply the code
3. run plan and see the diff appears

### Important Factoids

Commenting the `attribute_statements` block after initial provisioning of the resource stops the diffs from showing up, but not really a fix.

### LINKED ISSUE #418: Okta saml app attribute_statements ignored or not applying
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.35.0
+ provider registry.terraform.io/oktadeveloper/okta v3.10.1
```

### Affected Resource(s)

- okta_app_saml

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "bomgar" {
  label             = "Bomgar"
  preconfigured_app = "bomgarsaml"
  app_settings_json = jsonencode(
    {
      baseUrl             = "example.org"
      emailAttributeValue = "true"
    }
  )
  attribute_statements {
    type         = "GROUP"
    name         = "Groups"
    filter_type  = "REGEX"
    filter_value = ".*"
    namespace    = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
  }
}
```

### Expected Behavior

Configure the group match show on step 13 of the okta-bomgar integration [documentation](https://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Bomgar.html). 
image

### Actual Behavior

The attribute statement is ignored or does not apply. 

### Steps to Reproduce

1. create an okta_app_saml with a preconfigured_app (bomgarsaml)
2. apply the code

### Important Factoids

I've attempted to configure the okta application from the okta console and then run `terraform import` to see if that group match configuration gets imported but it does not seem to be included on the state.

### PR DESCRIPTION
**Pull request by bogdanprodan-okta**
To enable attribute statements for pre-configured apps you have to enable these two flags in your org: `ENABLE_APP_WIZARD_NEW_ENTRY_PATH` and `ENABLE_APP_WIZARD_NEW_FORM`

Fix #418 
Fix #415

### CODE REVIEW

**Review by bretterer — APPROVED** [review]

**Comment by dkulchinsky** [comment]
@bogdanprodan-okta just want to confirm that you refer to these options?
image

**Comment by liath** [comment]
Any idea when this is going to be released?

**Comment by bogdanprodan-okta** [comment]
Hi @Liath! Unfortunately, I can't give you the exact time, because we still waiting for a new gpg key from Hashicorp.

**Comment by liath** [comment]
Neat! Out of curiosity, how does that work? Are there some cool Hashicorp branded yubikeys floating around? :)

**Comment by plynch-magnolia** [comment]
These options are not available in the Admin Features section....and attribute statements are also not working

**Comment by dkulchinsky** [comment]
> These options are not available in the Admin Features section....and attribute statements are also not working

I don't see these options anymore, however they were there when I posted the screenshot back in April https://github.com/okta/terraform-provider-okta/pull/439#issuecomment-825936593

as for the attribute statements, according to the comment here https://github.com/okta/terraform-provider-okta/issues/415#issuecomment-849442670 from @bogdanprodan-okta, this feature was merged but didn't land in the latest release (v3.11.1)

**Pull request merged**
