### PR TITLE
Diff Suppression on SLO Certs

### PR DESCRIPTION
**Pull request by ymylei**
- Okta API returns the certificate on the API response in the MIME format.
- Okta API will accept certs in a variety of formats, in scope here are passing the certificate as a PEM block and the raw DER

Therefore, if you do not send the certificate in the same format the API returns it as, this will diff unnecessarily. 

This diff suppression is intended to convert the various values of the cert into the Go recognised certificate format, then if the old and new values are "equal", we can suppress this diff.

### CODE REVIEW

**Comment by ymylei** [comment]
`commit 36fa16a82f4e47f5df094f9cda14047f98f708d7 (HEAD -> certificate-diff-supress, origin/certificate-diff-supress)
`
```
➜  terraform-provider-okta git:(certificate-diff-supress) TEST_FILTER="TestAccAppSaml" make testacc              
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -run TestAccAppSaml -timeout 120m
?       github.com/okta/terraform-provider-okta [no test files]
=== RUN   TestAccAppSamlAppSettings_crud
--- PASS: TestAccAppSamlAppSettings_crud (23.70s)
=== RUN   TestAccAppSaml_conditionalRequire
--- PASS: TestAccAppSaml_conditionalRequire (3.58s)
=== RUN   TestAccAppSaml_invalidURL
--- PASS: TestAccAppSaml_invalidURL (1.58s)
=== RUN   TestAccAppSaml_crud
--- PASS: TestAccAppSaml_crud (75.95s)
=== RUN   TestAccAppSaml_preconfigured
--- PASS: TestAccAppSaml_preconfigured (13.83s)
=== RUN   TestAccAppSaml_userGroups
--- PASS: TestAccAppSaml_userGroups (51.21s)
=== RUN   TestAccAppSaml_inlineHook
--- PASS: TestAccAppSaml_inlineHook (12.12s)
=== RUN   TestAccAppSaml_federationBroker
    resource_okta_app_saml_test.go:309: This is an 'Early Access Feature' and needs to be enabled by Okta, skipping this test as it fails when this feature is not available
--- SKIP: TestAccAppSaml_federationBroker (0.00s)
=== RUN   TestAccAppSaml_certdiff
=== PAUSE TestAccAppSaml_certdiff
=== CONT  TestAccAppSaml_certdiff
--- PASS: TestAccAppSaml_certdiff (56.76s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    238.956s
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/apimutex  (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/mutexkv   (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/transport (cached) [no tests to run]
?       github.com/okta/terraform-provider-okta/sdk     [no test files]
```

**Comment by monde** [comment]
ACK https://github.com/okta/terraform-provider-okta/pull/1273#issuecomment-1230566754

**Review by monde — COMMENTED** [review]
**OIE**

```
TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^TestCertNormalize$ ./okta 2>&1
=== RUN   TestCertNormalize
--- PASS: TestCertNormalize (0.00s)
PASS
ok

for t in `grep "func Test" okta/resource_okta_app_saml_test.go | awk '{ print $2}'| sed -e 's/(.*//g'`; do
TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^${t} ./okta
done
=== RUN   TestAccAppSaml_conditionalRequire
--- PASS: TestAccAppSaml_conditionalRequire (2.04s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    2.299s
=== RUN   TestAccAppSaml_invalidURL
--- PASS: TestAccAppSaml_invalidURL (0.18s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    0.438s
=== RUN   TestAccAppSaml_crud
--- PASS: TestAccAppSaml_crud (37.65s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    37.907s
=== RUN   TestAccAppSaml_preconfigured
--- PASS: TestAccAppSaml_preconfigured (11.30s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    11.553s
=== RUN   TestAccAppSaml_userGroups
--- PASS: TestAccAppSaml_userGroups (19.66s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    19.904s
=== RUN   TestAccAppSaml_inlineHook
--- PASS: TestAccAppSaml_inlineHook (9.63s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    9.868s
=== RUN   TestAccAppSaml_federationBroker
    resource_okta_app_saml_test.go:309: This is an 'Early Access Feature' and needs to be enabled by Okta, skipping this test as it fails when this feature is not available
--- SKIP: TestAccAppSaml_federationBroker (0.00s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    (cached)
=== RUN   TestAccResourceOktaAppSaml_timeouts
--- PASS: TestAccResourceOktaAppSaml_timeouts (8.42s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    8.667s
=== RUN   TestAccAppSaml_certdiff
=== PAUSE TestAccAppSaml_certdiff
=== CONT  TestAccAppSaml_certdiff
--- PASS: TestAccAppSaml_certdiff (22.57s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    22.815s
```

**Classic**

```
TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^TestCertNormalize$ ./okta 2>&1
=== RUN   TestCertNormalize
--- PASS: TestCertNormalize (0.00s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    (cached)

for t in `grep "func Test" okta/resource_okta_app_saml_test.go | awk '{ print $2}'| sed -e 's/(.*//g'`; do
  TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^${t} ./okta
done
=== RUN   TestAccAppSaml_conditionalRequire
--- PASS: TestAccAppSaml_conditionalRequire (2.29s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    2.539s
=== RUN   TestAccAppSaml_invalidURL
--- PASS: TestAccAppSaml_invalidURL (0.18s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    (cached)
=== RUN   TestAccAppSaml_crud
--- PASS: TestAccAppSaml_crud (35.36s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    35.602s
=== RUN   TestAccAppSaml_preconfigured
--- PASS: TestAccAppSaml_preconfigured (11.72s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    12.137s
=== RUN   TestAccAppSaml_userGroups
--- PASS: TestAccAppSaml_userGroups (19.49s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    19.741s
=== RUN   TestAccAppSaml_inlineHook
--- PASS: TestAccAppSaml_inlineHook (9.23s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    9.488s
=== RUN   TestAccAppSaml_federationBroker
    resource_okta_app_saml_test.go:309: This is an 'Early Access Feature' and needs to be enabled by Okta, skipping this test as it fails when this feature is not available
--- SKIP: TestAccAppSaml_federationBroker (0.00s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    (cached)
=== RUN   TestAccResourceOktaAppSaml_timeouts
--- PASS: TestAccResourceOktaAppSaml_timeouts (8.31s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    8.563s
=== RUN   TestAccAppSaml_certdiff
=== PAUSE TestAccAppSaml_certdiff
=== CONT  TestAccAppSaml_certdiff
--- PASS: TestAccAppSaml_certdiff (21.28s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    21.516s
```

**Review by monde — APPROVED** [review]
Thank you for the PR @ymylei and thanks for the tests.

**Pull request merged**
