### PR TITLE
feat: add support for samaccountname

### PR DESCRIPTION
**Pull request by achachw**
Hi there,
A simple contribution to add support for samaccountname as user attribut.
What do you think about ?

### CODE REVIEW

**Comment by virgofx** [comment]
@achachw I'm not sure the purpose of this. It appears based on [this](https://help.okta.com/en/prod/Content/Topics/Directory/Directory_AD_Field_Mappings.htm) that the samaccountname is derived. If you want it as an attribute on the user, just add a user schema property yourself and you're set. Wouldn't that solve your issue?

**Comment by achachw** [comment]
@virgofx  Thanks for your feedback.
I will need to check how this "samaccountname" property is added and try to understand further this "schema property". 
Basically with this MR i tried to get from datasource this attribut.

**Comment by achachw** [comment]
@virgofx  Finally this attribut is now added as schema property. We will use it.
Thanks and sorry for the noise.

**Comment by virgofx** [comment]
Awesome. I'm glad you have a workaround and thanks for the follow up!

**Pull request closed without merging**
