### PR TITLE
Added Group related example

### PR DESCRIPTION
**Pull request by pm-bhatt**
I have added this comment because there was no guidance on the document where in it shows that how to assign specific groups in resource set

This will be helpful to implement PLoP when we want to grant access to help-desk admins to specific groups only rather then all groups.

### CODE REVIEW

**Comment by pm-bhatt** [comment]
[Okta-Pratik Signed Agreement.pdf](https://github.com/user-attachments/files/16493312/Okta-Pratik.Signed.Agreement.pdf)

**Review by duytiennguyen-okta — DISMISSED** [review]

**Comment by pm-bhatt** [comment]
@duytiennguyen-okta : Request to kindly approve so that it can be merged please.

**Review by duytiennguyen-okta — DISMISSED** [review]

**Comment by duytiennguyen-okta** [comment]
@pm-bhatt you need to sign your commit

**Comment by pm-bhatt** [comment]
Hi @duytiennguyen-okta 

Apology for disturbing you again, I have now committed with Signed Signature with little modification. Can you please approve?

**Comment by pm-bhatt** [comment]
Hi @duytiennguyen-okta 

Apology for disturbing you again, I have now committed with Signed Signature with little modification. Can you please approve?

**Comment by pm-bhatt** [comment]
@duytiennguyen-okta @monde : Apology for disturbing you again, I have now committed with Signed Signature with little modification. Can you please approve?

**Review by duytiennguyen-okta — APPROVED** [review]

**Comment by duytiennguyen-okta** [comment]
@pm-bhatt I tried to approve but github still require the commit to be sign. I can just take your work and bring it in if that's easier for you

**Comment by pm-bhatt** [comment]
Yes sure, I don't have any problem

**Pull request closed without merging**
