### PR TITLE
Adding support for SMS template changes in Okta terraform plugin

### PR DESCRIPTION
**Pull request by gustavo-chan**
A new resource to add SMS template resource to okta terraform plugin.

### CODE REVIEW

**Comment by gustavo-chan** [comment]
Hi @noinarisak , If you could also stage this PR for review. It would be greatly appreciated. Thanks!

**Comment by noinarisak** [comment]
Hi @gusChan, thanks again for submitting this PR. @quantumew and I looked at your PR and have one request. Could you submit `examples/okta_template_sms/update.tf` file with an associated unit test to validate the an update action? @quantumew and I are hoping to have more update.tf like files with unit tests to make things better. 

Thanks again!

**Comment by gustavo-chan** [comment]
@noinarisak I have updated the acceptance test with an updated.tf . Please review.

Thanks!

**Comment by noinarisak** [comment]
Hi @gusChan sorry being MIA. Things are getting somewhat normal (whatever that means) for me and slowly getting back on track with this project. This pandemic really sucks. 

In short, merging your PR! Thanks again!

**Pull request merged**
