### PR TITLE
Support Custom Group Profile Schema

### PR DESCRIPTION
**Pull request by ymylei**
PR is designed to:

- Re-use the design/logic for the `custom_profile_attributes` from `okta_user` and implement in `okta_group`

### CODE REVIEW

**Comment by ymylei** [comment]
@bogdanprodan-okta @monde QQ for you regarding this PR. I see the version of the SDK you're currently using is some custom version of the `2.9.2` SDK, however it's missing the `GroupProfileMap` from the official release (https://github.com/okta/okta-sdk-golang/releases/tag/v2.9.2). 

Would y'all mind weighing in on how we should proceed here? I noticed that if I manually swapped to the normal release, there were type issues and other things raised, so it's deviated further than I expected.

**Comment by bogdanprodan-okta** [comment]
> @bogdanprodan-okta @monde QQ for you regarding this PR. I see the version of the SDK you're currently using is some custom version of the `2.9.2` SDK, however it's missing the `GroupProfileMap` from the official release (https://github.com/okta/okta-sdk-golang/releases/tag/v2.9.2).
> 
> Would y'all mind weighing in on how we should proceed here? I noticed that if I manually swapped to the normal release, there were type issues and other things raised, so it's deviated further than I expected.

@ymylei currently, a generator that is used to generate SDK's codebase is not very flexible, so I keep some manual changes in a separate branch. This is necessary for the correct behavior of the provider. I've created PR #852 that contains all the necessary fields.

**Comment by ymylei** [comment]
> > @bogdanprodan-okta @monde QQ for you regarding this PR. I see the version of the SDK you're currently using is some custom version of the `2.9.2` SDK, however it's missing the `GroupProfileMap` from the official release (https://github.com/okta/okta-sdk-golang/releases/tag/v2.9.2).
> > Would y'all mind weighing in on how we should proceed here? I noticed that if I manually swapped to the normal release, there were type issues and other things raised, so it's deviated further than I expected.
> 
> @ymylei currently, a generator that is used to generate SDK's codebase is not very flexible, so I keep some manual changes in a separate branch. This is necessary for the correct behavior of the provider. I've created PR #852 that contains all the necessary fields.

Cheers! Much appreciated!

**Comment by ymylei** [comment]
@bogdanprodan-okta @monde Pretty sure this is ready to go, notifying you since my tests were producing some errors but passing. Based on the messages I suspect it's just weird behavior from the `okta_group_schema_property` & associated API.

**Comment by ymylei** [comment]
Updated test results:
```
➜  terraform-provider-okta git:(group-profile) ✗ TEST_FILTER="TestAccOktaGroup_customschema" make testacc
go mod tidy
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -run TestAccOktaGroup_customschema -timeout 120m
?       github.com/okta/terraform-provider-okta [no test files]
=== RUN   TestAccOktaGroup_customschema
2021/12/09 09:13:03 [ERROR] failed to apply changes after several retries
2021/12/09 09:13:03 [ERROR] failed to apply changes after several retries
2021/12/09 09:13:41 [ERROR] failed to apply changes after several retries
2021/12/09 09:13:41 [ERROR] failed to apply changes after several retries
--- PASS: TestAccOktaGroup_customschema (43.54s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    43.788s
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/apimutex  (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/transport (cached) [no tests to run]
?       github.com/okta/terraform-provider-okta/sdk     [no test files]
```

**Comment by bogdanprodanj** [comment]
@ymylei I would suggest adding `depends_on` to the `okta_group` resource. It will enable creating custom attributes along with `okta_group`. Another option would be using `index` values themselves in the `okta_group`.
```
resource "okta_group" "test" {
  name        = "testAcc_replace_with_uuid"
  description = "testing, testing"
  custom_profile_attributes = jsonencode({
    format("%s", okta_group_schema_property.test1.index) = "testing1234",
  })
}

resource "okta_group_schema_property" "test1" {
  index       = "testSchema1_replace_with_uuid"
  title       = "TestSchema1_replace_with_uuid"
  type        = "string"
  description = "Test string schema"
  master      = "OKTA"
}
```

**Comment by ymylei** [comment]
@bogdanprodan-okta Good shout! I used the index values and was able to streamline the test. Updated results here:

```
➜  terraform-provider-okta git:(group-profile) ✗ TEST_FILTER="TestAccOktaGroup_customschema" make testacc
go mod tidy
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -run TestAccOktaGroup_customschema -timeout 120m
?       github.com/okta/terraform-provider-okta [no test files]
=== RUN   TestAccOktaGroup_customschema
2021/12/11 01:08:36 [ERROR] failed to apply changes after several retries
2021/12/11 01:08:36 [ERROR] failed to apply changes after several retries
--- PASS: TestAccOktaGroup_customschema (29.14s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    29.387s
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/apimutex  (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/transport (cached) [no tests to run]
?       github.com/okta/terraform-provider-okta/sdk     [no test files]
```

**Comment by ymylei** [comment]
Results of `TestAccOktaGroup_crud` to confirm no breaking changes to the resource behavior:

```
➜  terraform-provider-okta git:(group-profile) TEST_FILTER="TestAccOktaGroup_crud" make testacc
go mod tidy
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -run TestAccOktaGroup_crud -timeout 120m
?       github.com/okta/terraform-provider-okta [no test files]
=== RUN   TestAccOktaGroup_crud
--- PASS: TestAccOktaGroup_crud (29.58s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    29.824s
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/apimutex  0.191s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/transport 0.135s [no tests to run]
?       github.com/okta/terraform-provider-okta/sdk     [no test files]
```

**Review by bogdanprodan-okta — APPROVED** [review]

**Pull request merged**
