### PR TITLE
Issue 1392: add support for log stream resource and data

### PR DESCRIPTION
**Pull request by randomVariable2**
Adds data and resource for Okta [Log Streams](https://developer.okta.com/docs/api/openapi/okta-management/management/tag/LogStream/)
#1392

### CODE REVIEW

**Comment by randomVariable2** [comment]
@duytiennguyen-okta @monde Can you have a look?

**Comment by monde** [comment]
@randomVariable2 I'm going to bring your original work in on a separate PR. Do you have a CLA on file with us? https://developer.okta.com/cla/

**Comment by monde** [comment]
Okta internal reference https://oktainc.atlassian.net/browse/OKTA-671289

**Comment by randomVariable2** [comment]
> @randomVariable2 I'm going to bring your original work in on a separate PR. Do you have a CLA on file with us? https://developer.okta.com/cla/

@monde I hadn't, but I sent the e-mail after your comment

**Comment by monde** [comment]
Thanks @randomVariable2 I see your CLA, thank you.

**Comment by monde** [comment]
Merged this original work in as #1843 "Converting PR #1830 to v3 okta-sdk-golang and Terraform Plugin Framework"

**Pull request closed without merging**
