### PR TITLE
oauth app refresh token settings

### LINKED ISSUE #465: resource_okta_app_oauth does not allow setting "refresh_token"  as grant type for browser app when Refresh token rotation is enabled.
resource_okta_app_oauth does not allow setting "refresh_token"  as grant type for browser app. 

This feature is indeed not available, unless enabling the setting for Refresh token rotation.

Once Refresh token rotation has been activated, I should be able to add "refresh_token" to grant type.

Limitation is seen in okta/resource_okta_app_oauth.go

	"browser": {
		ValidGrantTypes: []string{
			implicit,
			authorizationCode,
		},

In the meanwhile, once I enable the refresh_token grant type in the web UI, I can no longer use terraform which either removes it, or fails the validation. 

Thanks,

### PR DESCRIPTION
**Pull request by jeffg-archive**
See https://developer.okta.com/docs/guides/refresh-tokens/refresh-token-rotation/ in particular [this](https://developer.okta.com/docs/guides/refresh-tokens/refresh-token-rotation/).

This is an early access feature.

### CODE REVIEW

**Comment by bogdanprodan-okta** [comment]
> > **WIP** / proposal for discussion
> 
> See also #465
> 
> Will depend on #466
> 
> See https://developer.okta.com/docs/guides/refresh-tokens/refresh-token-rotation/ in particular [this](https://developer.okta.com/docs/guides/refresh-tokens/refresh-token-rotation/).
> 
> This is an early access feature.

It's available in the official SDK, so it's fine to add it.
FYI
`vendor/github.com/okta/okta-sdk-golang/v2/okta/openIdConnectApplicationSettingsClient.go:34`

**Comment by jeffg-archive** [comment]
Passing acceptance tests for me, including the _refresh test I added in this PR (manually remove the Skip statement if your acceptance test org has this early access feature enabled).

```
$ make testacc TESTARGS='-run=TestAccAppOauth_refresh'
go mod tidy
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccAppOauth_refresh  -timeout 120m
?       github.com/okta/terraform-provider-okta [no test files]
=== RUN   TestAccAppOauth_refreshToken
--- PASS: TestAccAppOauth_refreshToken (9.81s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    10.078s
?       github.com/okta/terraform-provider-okta/sdk     [no test files]
```

**Comment by bogdanprodan-okta** [comment]
@jeffg-hpe don't forget to update the [docs.](https://github.com/okta/terraform-provider-okta/blob/master/website/docs/r/app_oauth.html.markdown#argument-reference)

**Comment by bogdanprodan-okta** [comment]
Hi, @jeffg-hpe! Hope you don't mind, but I've added validation and updated Okta golang SDK version. The problem was that `Leeway int64 'json:"leeway"'` field had an `omitemty` thus it was impossible to set `0` for that field.

**Review by bogdanprodan-okta — APPROVED** [review]

**Pull request merged**
