### PR TITLE
Chore: Format Terraform Files

### PR DESCRIPTION
**Pull request by tgoodsell-tempus**
Formatting the Terraform files here, so they're in a decent shape and future format runs don't try to fix all of these along with the target files.

### CODE REVIEW

**Comment by monde** [comment]
@tgoodsell-tempus did you do this by hand (😲) or with some tf config linter/formatter (😎)

**Review by monde — APPROVED** [review]
Awesome, thank you @tgoodsell-tempus

**Comment by monde** [comment]
I need to cherry pick this into a branch I own due to branch merging protections, fyi

**Comment by tgoodsell-tempus** [comment]
> @tgoodsell-tempus did you do this by hand (😲) or with some tf config linter/formatter (😎)

@monde I use a alias (I'm a `zsh` user) such as:
```zsh
def tfmt() {
    terraform fmt --recursive
}
```

I've a few other combo aliases I use when commiting code and so on to make sure that's run when I'm working on stuff like this. Would highly recommend from a workflow standpoint:

For example, I have a commit alias which does:
```zsh
terraform fmt --recursive
git add -A
git commit -m "$1" (message from my shell)
git push -u origin
```

and so on

**Pull request closed without merging**
