### PR TITLE
Removed articulate okta SDK

### PR DESCRIPTION
**Pull request by bogdanprodan-okta**

### CODE REVIEW

**Comment by bryantbiggs** [comment]
this looks awesome, incredible work @bogdanprodan-okta - @noinarisak any chance we could get this merged and released under `v3.6.1` today?

**Comment by bogdanprodan-okta** [comment]
> this looks awesome, incredible work @bogdanprodan-okta - @noinarisak any chance we could get this merged and released under `v3.6.1` today?

We are still waiting for a new version okta-sdk-golang to be published, as it contains a fix related to the rate-limiting issue.

**Comment by bryantbiggs** [comment]
@bogdanprodan-okta is this the patch that we're waiting on https://github.com/okta/okta-sdk-golang/pull/182 ?

**Comment by bogdanprodan-okta** [comment]
> @bogdanprodan-okta is this the patch that we're waiting on [okta/okta-sdk-golang#182](https://github.com/okta/okta-sdk-golang/pull/182) ?

Yes, it is

**Comment by bryantbiggs** [comment]
sorry to be a pain, but it looks like the changes landed -https://github.com/okta/okta-sdk-golang/releases/tag/v2.2.0 - just hoping to get some of these fixes in because I am importing a large amount of changes for a client and these will help a lot of issues we are seeing in the diffs

**Comment by bogdanprodan-okta** [comment]
I will merge this PR within several hours, just need to be sure that all the acceptance tests will pass.

**Comment by bryantbiggs** [comment]
@bogdanprodan-okta / @noinarisak could we get a new release with the number of changes since v3.6.0 when you get a chance, please?

**Comment by bogdanprodan-okta** [comment]
> @bogdanprodan-okta / @noinarisak could we get a new release with the number of changes since v3.6.0 when you get a chance, please?

Hi @bryantbiggs! Today we will release these changes with tag v3.6.1

**Pull request merged**
