### PR TITLE
Added login_mode and login_scopes to the `app_oauth`

### LINKED ISSUE #57: Missing parameter 'Login initiated by'
*@wiciu125 commented on Oct 28, 2019, 9:39 PM UTC:*

When configuring OAUTH in terraform there is no option to define `Login initiated by` parameter.
After successfully creating application the default option for it is "App only".
As a result, when trying to open page by clicking on application in okta an error 404 appears.
To change it to "Either Okta or App" manual action is required from the okta admin page.

The below configuration is for our Grafana

```
resource "okta_app_oauth" "grafana" {
  label                      = "Grafana"
  type                       = "web"
  grant_types                = ["authorization_code", "implicit"]
  redirect_uris              = ["https://URLTOTHEGRAFANA/login/generic_oauth"]
  response_types             = ["code", "id_token"]
  token_endpoint_auth_method = "client_secret_basic"
  login_uri                  = "https://URLTOTHEGRAFANA"
  hide_web                   = true
}

```

*This issue was moved by [noinarisak](https://github.com/noinarisak) from [articulate/terraform-provider-okta#310](https://github.com/articulate/terraform-provider-okta/issues/310).*

### LINKED ISSUE #306: Add parameter for "Login initiated by" to the okta_app_oauth resource
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add parameter for "Login initiated by" to the okta_app_oauth resource.

When configuring the okta_app_oauth resource in terraform there is no option to define "Login initiated by" parameter and the default is set to "App only", which means that when trying to open a page by clicking on application in Okta a 404 error appears.

This has been mentioned a few times before in #57  and #89 but perhaps the general Okta API didn't support this at the time, however it appears to now: https://developer.okta.com/docs/reference/api/apps/#idp-initiated-login-object 

### New or Affected Resource(s)
- okta_app_oauth

### References
https://github.com/oktadeveloper/terraform-provider-okta/issues/57
https://github.com/oktadeveloper/terraform-provider-okta/issues/89
https://developer.okta.com/docs/reference/api/apps/#idp-initiated-login-object

### PR DESCRIPTION
**Pull request by bogdanprodan-okta**
Fix #306

### CODE REVIEW

**Comment by jeremie0** [comment]
why is login_scopes required when login_mode = SPEC?  According to the API docs, default_scope  is only needed when mode = OKTA.

**Comment by bogdanprodan-okta** [comment]
Hi @jeremie0! Thanks for noticing this! I'll create a PR with the fix shortly.

**Comment by bogdanprodan-okta** [comment]
Hi, @jeremie0! I've commented out the check for the scopes and this is what  I get:
```
Error: failed to update OAuth application: The API returned an error: Api validation failed: default_scope. Causes: errorSummary: default_scope: 'default_scope' is required.
```
TF file:
```HCL
resource "okta_app_oauth" "test" {
  label                      = "testAcc_replace_with_uuid"
  type                       = "web"
  grant_types                = [
    "implicit",
    "authorization_code"]
  redirect_uris              = [
    "http://d.com/"]
  response_types             = [
    "code",
    "token"]
  client_basic_secret        = "something_from_somewhere"
  client_id                  = "something_from_somewhere"
  token_endpoint_auth_method = "client_secret_basic"
  consent_method             = "TRUSTED"
  login_uri                  = "http://d.com/login"
  login_mode                 = "SPEC"
}
```

By adding `login_scopes = ["email"]` error goes away. I think it's either I'm doing something wrong, or the docs are inaccurate.

**Comment by jeremie0** [comment]
thanks for checking @bogdanprodan-okta. It's interesting because a GET /api/v1/apps/appid API call against an existing oauth app that has "Login initiated by Either Okta or App"  enabled (via UI before we could change w/terraform)  has:
```
            "idp_initiated_login": {
                "mode": "SPEC",
                "default_scope": []
            }
```
so it seems that an empty list should be valid.

**Comment by bogdanprodan-okta** [comment]
> thanks for checking @bogdanprodan-okta. It's interesting because a GET /api/v1/apps/appid API call against an existing oauth app that has "Login initiated by Either Okta or App" enabled (via UI before we could change w/terraform) has:
> 
> ```
>             "idp_initiated_login": {
>                 "mode": "SPEC",
>                 "default_scope": []
>             }
> ```
> 
> so it seems that an empty list should be valid.

Seems like you are right. The only problem is that the model for Golang SDK should be changed accordingly:
```
type OpenIdConnectApplicationIdpInitiatedLogin struct {
	DefaultScope []string `json:"default_scope,omitempty"` // <-- because of 'omitempty' you can not provide an emty list
	Mode         string   `json:"mode,omitempty"`
}
```
I'll try to get this change into official SDK and then create PR here.

Thanks again for your comments!!

**Comment by bogdanprodan-okta** [comment]
@jeremie0 #333

**Comment by jeremie0** [comment]
@bogdanprodan-okta  in trying to use this, I am running into an issue.  If I have:
```
  login_mode                 = "SPEC"
  login_scopes                = []
```

the okta api gives an error:
```
Error: failed to update OAuth application: The API returned an error: Api validation failed: default_scope. Causes: errorSummary: default_scope: 'default_scope' is required.
```

in the tf apply debug output it is sending:
```
   "idp_initiated_login": {
    "default_scope": null,
    "mode": "SPEC"
   },
```

do you know how I can get it to send [] instead of null?

**Comment by bogdanprodan-okta** [comment]
Hi, @jeremie0! Totally my fault! I've used the wrong function [here ](https://github.com/oktadeveloper/terraform-provider-okta/pull/352/files#diff-4a5904220b736cd8cd158c3c3e4814fda830aff6ccae710cecbd52aedcac897cR550). I'll include this fix in the next minor release. Thanks for the comment!

**Comment by bogdanprodan-okta** [comment]
Hi, @jeremie0! I've included this fix in the latest v3.10.1 release.

**Comment by jeremie0** [comment]
thank you! I just tested with 3.10.1 and it's working as expected.

**Pull request merged**
