### PR TITLE
okta_app_auto_login enhancements

### PR DESCRIPTION
**Pull request by isometry**
* Enhance `okta_app_auto_login` resource by adding support for user and group assignment, and allowing the `user_name_template*` attributes to be overridden.
* Add missing arguments to `okta_app_auto_login` documentation.
* Refactor `buildSchema()` as variadic to simplify schema logic.

### CODE REVIEW

**Comment by hrzbrg** [comment]
Hey, thanks for adding all these to the okta_app_auto_login, we would really love to see it in the provider as soon as possible, as we have teams requesting addition of such apps and currently it is still a manual task. In the future they can just hand in PRs for this :)

**Comment by bryantbiggs** [comment]
any thoughts @bogdanprodan-okta / @noinarisak ?

**Comment by isometry** [comment]
We've been using the changes in this PR as a critical part of our Okta configuration since we migrated in August… I'll feel far more comfortable once this is merged and we no longer have to maintain a custom provider mirror incorporating these changes.

**Comment by bogdanprodan-okta** [comment]
Hi @isometry! Thanks for the PR! Could you please add or edit a test case for this functionality? 

PS I've already tested it on a test company with updated test cases and it's working as expected

**Comment by bogdanprodan-okta** [comment]
@noinarisak I think this PR is ready to be merged.

**Pull request merged**
