### PR TITLE
add datasource default signin page

### PR DESCRIPTION
**Pull request by duytiennguyen-okta**

### CODE REVIEW

**Review by monde — APPROVED** [review]

**Comment by thatguysimon** [comment]
Hi @duytiennguyen-okta @monde, thanks for this great feature! Is it ready to be used in production? I don't see it in the documentation 🤔

**Comment by hueydn** [comment]
Yes we've been waiting for this feature and now that it is here there is no documentation update on how it is used.

**Comment by duytiennguyen-okta** [comment]
That should already be available. I'm not sure why the doc not showing up, but you see the doc page here https://github.com/okta/terraform-provider-okta/blob/master/docs/data-sources/default_signin_page.md

**Comment by hueydn** [comment]
> That should already be available. I'm not sure why the doc not showing up, but you see the doc page here https://github.com/okta/terraform-provider-okta/blob/master/docs/data-sources/default_signin_page.md

That looks like the data-sources documentation is where is the resources documentation?

Also will this resource manage the new content security policy settings we see in preview tenants right now?

**Comment by thatguysimon** [comment]
Hey @duytiennguyen-okta, any updates on why this isn't showing up in the official docs?
I'm getting an error trying to use the new _resource_, and hesitant about opening an issue for an "undocumented" feature.
Thanks!

**Comment by duytiennguyen-okta** [comment]
I'm talking with hashicorp about that

**Comment by thatguysimon** [comment]
Hi @duytiennguyen-okta, any news from hashicorp on this?

**Comment by duytiennguyen-okta** [comment]
They said they are looking into it

**Comment by hueydn** [comment]
will this feature also support the CSP policies

**Comment by duytiennguyen-okta** [comment]
What is that?

**Comment by hueydn** [comment]
> What is that?

The new Content Security Policy settings so you can trust calls to third party URLs from the signin page:
Screenshot 2024-04-12 at 12 33 55 PM

**Comment by hueydn** [comment]
I saw 8.1 was released recently but yet there is no updated documentation on how this feature is used...

**Comment by hueydn** [comment]
Is this forever going to remain an undocumented feature? I looked at the commit and was able to determine how it works however there are still some unknowns to me... When will the docs be updated? I see 4.8.1 was released but I still don't see the docs for this which was 3 releases ago.

**Comment by bhavik-thakkar-okta** [comment]
Hey @huy-keydata , we have the updates added in the ReadMe section but we are currently working with HashiCorp to get this added to their docs as well. In the meantime, you can find the updates in our ReadMe as mentioned above.

**Pull request merged**
