### PR TITLE
add data.okta_groups for listing groups

### PR DESCRIPTION
**Pull request by bendrucker**
This PR adds `data.okta_groups`, which implements [group searching](https://developer.okta.com/docs/reference/api/groups/#search-groups). It includes an acceptance test and documentation.

## Use Case

I'd like to use this alongside Terraform Cloud's [`tfe_team`](https://www.terraform.io/docs/providers/tfe/r/team.html) resource. Terraform Cloud has its own "Team" object. When [using SAML for login](https://www.terraform.io/docs/enterprise/saml/team-membership.html), users are assigned to teams based on a `MemberOf` attribute in the SAML response. This means that Terraform Cloud administrators need to define teams whose names exactly match corresponding groups from Okta.

```tf
data "okta_groups" "engineering" {
  q = "Engineering - "
}

resource "tfe_team" "test" {
  for_each = [for group in data.okta_groups.engineering.groups : group.name]

  name         = each.value
  organization = "my-org-name"
}
```

### CODE REVIEW

**Comment by bendrucker** [comment]
I opened a trial account to run the acceptance tests and was struggling with an "Invalid token provided" error that I couldn't resolve. I will run the added acceptance test if I can figure that out. Otherwise, realized I forgot to register the data source with the provider. Fixed that.

**Comment by bendrucker** [comment]
Figured out my auth issue. Resolved some minor issues with the test, can now confirm that it passes:

```
$ make testacc TEST=./okta TESTARGS='-run=TestAccOktaDataSourceGroups_read'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./okta -v -run=TestAccOktaDataSourceGroups_read  -timeout 120m
=== RUN   TestAccOktaDataSourceGroups_read
--- PASS: TestAccOktaDataSourceGroups_read (3.27s)
PASS
ok  	github.com/terraform-providers/terraform-provider-okta/okta
```

**Comment by bendrucker** [comment]
Let me know if there's anything else I should do here! This is more of a nice to have than an urgent need, but we'd still love to use it.

**Comment by bendrucker** [comment]
@noinarisak Any chance I could get a review here? At @takescoop we are finding we need group names for any SAML apps that support group assertions, including:

* Terraform Cloud/Terraform Enterprise (https://www.terraform.io/docs/providers/tfe/index.html)
* Artifactory (https://github.com/atlassian/terraform-provider-artifactory)
* GitHub (https://www.terraform.io/docs/providers/github)

Currently we have to specify a list of teams in code, even when we only want to provide override configuration for certain teams and give default permissions to others (i.e. read-only).

**Comment by bendrucker** [comment]
Closing this based on age, always happy to come back to it!

**Comment by fatbasstard** [comment]
Hi @bendrucker ,

Was just looking for this "missing feature" and found this PR. This is exactly what I was looking for. Is there any chance you can reopen it?

Small ping to @bogdanprodan-okta for visibility

**Comment by bogdanprodan-okta** [comment]
> Hi @bendrucker ,
> 
> Was just looking for this "missing feature" and found this PR. This is exactly what I was looking for. Is there any chance you can reopen it?
> 
> Small ping to @bogdanprodan-okta for visibility

@fatbasstard! I'll add a few things in and fix the conflicts. I'll try to include this to the upcoming release. Cheers!

**Review by bogdanprodan-okta — APPROVED** [review]

**Pull request merged**
