### PR TITLE
Add missing valid custom role permissions

### PR DESCRIPTION
**Pull request by lucascantor**
Valid permissions are documented at https://developer.okta.com/docs/reference/api/roles/#permission-properties

### CODE REVIEW

**Comment by lucascantor** [comment]
Thanks for your patience with my first PR in the `terraform-provider-okta` repo. I took a look at the [contributing guidelines](https://github.com/okta/terraform-provider-okta/blob/master/.github/CONTRIBUTING.md#enhancementbugfix-to-a-resource) but don't see anything referencing `validCustomRolePermissions` in the existing [code](https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_admin_role_custom.go) or [tests](https://github.com/okta/terraform-provider-okta/blob/master/okta/resource_okta_admin_role_custom_test.go).

That said, if I'm missing anything, please let me know, and I'll do my best to add it 🙏🏼

**Comment by monde** [comment]
Thank you @lucascantor !

**Comment by lucascantor** [comment]
@monde I see I need approval before 1 workflow will run, as I'm a first-time contributor:

Screen Shot 2022-03-22 at 12 04 33 PM

**Comment by monde** [comment]
Hi @lucascantor , apologies for my slowness. Can you make strings in the `var validCustomRolePermissions` be alphabetized and have each element on a new line? I did something similar here on `validEmailTemplateTypes` https://github.com/okta/terraform-provider-okta/pull/1012/files

I think the workflow will fail when when we have it run on your cloned repo. I'll have to double check after the change, and might have to start a new branch and cherry pick in your commits.

**Comment by lucascantor** [comment]
@monde not a problem at all. I sincerely appreciate the help.

I believe I've made the change you're looking for now 👍🏼

**Review by monde — APPROVED** [review]
Looks good, will be easy to see changes in the future, thank you @lucascantor

**Comment by monde** [comment]
I'll get this into the next release @lucascantor , thank you!

**Comment by monde** [comment]
@lucascantor  this is released as [v3.23.0](https://github.com/okta/terraform-provider-okta/releases/tag/v3.23.0)

**Comment by lucascantor** [comment]
@monde I noticed and we're already using it - thanks so much!

**Pull request merged**
