### PR TITLE
feat: add `keys` attribute to `okta_app_saml` resource

### PR DESCRIPTION
**Pull request by ericnorris**
This pull request adds a `keys` attribute to the `okta_app_saml` resource. We've put the methods used to pull the data into `app.go`, so it could potentially be added to other `okta_app_*` resources, and also their matching data sources.

Our use case is in setting up [`org2org` with OAuth](https://developer.okta.com/docs/guides/secure-oauth-between-orgs/main/), where we'd like to create an `okta_app_saml` resource in one organization, and an `okta_app_oauth` service app in the other.

Without the `keys` attribute, we've resorted to manually calling the [`/credentials/keys`](https://developer.okta.com/docs/reference/api/apps/#list-key-credentials-for-application) endpoint and adding them as JWK blocks in `okta_app_oauth`. We'd prefer to have this process be as automated as possible, so adding the `keys` to the application resource made sense to us.

### CODE REVIEW

**Comment by monde** [comment]
Thanks for the PR @ericnorris ! Apologies for the slow reply as I'm just getting back from vacation. I should be able to look at this by the end of this week.

**Comment by ericnorris** [comment]
Hey @monde, apologies for the ping, but any chance you'd be able to take a look at this PR this week or next?

**Comment by monde** [comment]
got test confirmation from @ericnorris and @slichtenthal

```
=== RUN   TestAccAppSaml_conditionalRequire
--- PASS: TestAccAppSaml_conditionalRequire (5.35s)
PASS
ok  	github.com/okta/terraform-provider-okta/okta	5.647s
=== RUN   TestAccAppSaml_invalidURL
--- PASS: TestAccAppSaml_invalidURL (1.79s)
PASS
ok  	github.com/okta/terraform-provider-okta/okta	2.107s
=== RUN   TestAccAppSaml_crud
--- PASS: TestAccAppSaml_crud (55.85s)
PASS
ok  	github.com/okta/terraform-provider-okta/okta	56.183s
=== RUN   TestAccAppSaml_preconfigured
--- PASS: TestAccAppSaml_preconfigured (47.41s)
PASS
ok  	github.com/okta/terraform-provider-okta/okta	48.140s
=== RUN   TestAccAppSaml_userGroups
--- PASS: TestAccAppSaml_userGroups (33.04s)
PASS
ok  	github.com/okta/terraform-provider-okta/okta	33.404s
=== RUN   TestAccAppSaml_inlineHook
--- PASS: TestAccAppSaml_inlineHook (45.70s)
PASS
ok  	github.com/okta/terraform-provider-okta/okta	46.090s
=== RUN   TestAccAppSaml_federationBroker
    resource_okta_app_saml_test.go:302: This is an 'Early Access Feature' and needs to be enabled by Okta, skipping this test as it fails when this feature is not available
--- SKIP: TestAccAppSaml_federationBroker (0.00s)
PASS
ok  	github.com/okta/terraform-provider-okta/okta	0.407s
```

**Review by monde — APPROVED** [review]
good to go @ericnorris and @slichtenthal

**Comment by monde** [comment]
Released in https://github.com/okta/terraform-provider-okta/releases/tag/v3.32.0

**Pull request merged**
