### PR TITLE
Add ID to data.okta_users

### PR DESCRIPTION
**Pull request by cgetzen**
data.okta_user gives access to the id element, but data.okta_users does not. This PR is the smallest change necessary to get the id element on data.okta_users.

### CODE REVIEW

**Comment by cgetzen** [comment]
@thehunt33r  @noinarisak  @mbfrahry  Would love your opinion on the PR or linked issue :)

**Comment by noinarisak** [comment]
Thanks, @cgetzen, for this PR. However, I'm not sure it is required. You should be able to reference the `${okta_user.test.id}` like so. Is there an issue that is not working for you?

https://github.com/oktadeveloper/terraform-provider-okta/blob/master/examples/okta_app_user/basic_profile.tf#L34-L39

**Comment by lukeswilor** [comment]
@noinarisak - If we are needing a user id of a user created outside of a project, it seems like we would need this from the data source? For example, to search for a user and add them to a group. Or if you have another way to get this?

```
data "okta_user" "user" {
  search {
    name  = "profile.login"
    value = "some_user"
  }

}

resource "okta_group" "group" {
  name        = "some_group"
  users       = [data.okta_user.user.id]
}
```

**Comment by bryantbiggs** [comment]
@bogdanprodan-okta / @noinarisak this seems pretty straightforward and safe to merge - no?

**Comment by funnybirdman** [comment]
> @noinarisak - If we are needing a user id of a user created outside of a project, it seems like we would need this from the data source? For example, to search for a user and add them to a group. Or if you have another way to get this?
> 
> ```
> data "okta_user" "user" {
>   search {
>     name  = "profile.login"
>     value = "some_user"
>   }
> 
> }
> 
> resource "okta_group" "group" {
>   name        = "some_group"
>   users       = [data.okta_user.user.id]
> }
> ```

In reality this is a very inefficient operation and will very quickly yield api limiting issues. Instead it is much more efficient to get all of the IDs for users using a group.

**Comment by bryantbiggs** [comment]
@cgetzen you might want to rebase when you get a chance

**Comment by bogdanprodan-okta** [comment]
Hi @cgetzen! Sorry for the late response. As you may or may not know, the `id` attribute is a reserved word in terraform, so there is no point in duplicating it in the schema. Basically, this should work fine without any changes to the codebase
```tf
data "okta_user" "user" {
  search {
    name  = "profile.login"
    value = "bogdan.prodan@okta.com"
  }
}

resource "okta_group" "group" {
  name        = "some_group"
  users       = [data.okta_user.user.id]
}
```
State file:
```json
{
      "mode": "managed",
      "type": "okta_group",
      "name": "group",
      "provider": "provider[\"registry.terraform.io/oktadeveloper/okta\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "description": "",
            "id": "00gwda43ixJ2dNuay0h7",
            "name": "some_group",
            "users": [
              "00uulbehbeE52T4Ef0h7"
            ]
          },
          "private": "bnVsbA==",
          "dependencies": [
            "data.okta_user.user"
          ]
        }
      ]
    }
```

**Comment by bogdanprodan-okta** [comment]
> Hi @cgetzen! Sorry for the late response. As you may or may not know, the `id` attribute is a reserved word in terraform, so there is no point in duplicating it in the schema. Basically, this should work fine without any changes to the codebase
> 
> ```terraform
> data "okta_user" "user" {
>   search {
>     name  = "profile.login"
>     value = "bogdan.prodan@okta.com"
>   }
> }
> 
> resource "okta_group" "group" {
>   name        = "some_group"
>   users       = [data.okta_user.user.id]
> }
> ```
> 
> State file:
> 
> ```json
> {
>       "mode": "managed",
>       "type": "okta_group",
>       "name": "group",
>       "provider": "provider[\"registry.terraform.io/oktadeveloper/okta\"]",
>       "instances": [
>         {
>           "schema_version": 0,
>           "attributes": {
>             "description": "",
>             "id": "00gwda43ixJ2dNuay0h7",
>             "name": "some_group",
>             "users": [
>               "00uulbehbeE52T4Ef0h7"
>             ]
>           },
>           "private": "bnVsbA==",
>           "dependencies": [
>             "data.okta_user.user"
>           ]
>         }
>       ]
>     }
> ```

`id` support for data `okta_users` will be added in the upcoming v3.8.0

**Comment by cgetzen** [comment]
Resolved with https://github.com/oktadeveloper/terraform-provider-okta/pull/288. Thanks!

**Pull request closed without merging**
