### PR TITLE
Upgrade to Okta SDK 2.0.0

### PR DESCRIPTION
**Pull request by bogdanprodan-okta**

### CODE REVIEW

**Comment by noinarisak** [comment]
@bogdanprodan-okta Can you commit the `vendor/modules.txt` file? I had to `make build` to able to execute the acc test.

**Comment by bogdanprodan-okta** [comment]
> @bogdanprodan-okta Can you commit the `vendor/modules.txt` file? I had to `make build` to able to execute the acc test.

I can add `make dep` task so it will install dependencies prior to `testacc`

**Review by bryantbiggs — APPROVED** [review]

**Comment by bryantbiggs** [comment]
great to see some progress happening!

**Review by noinarisak — APPROVED** [review]
LGTM!

**Pull request merged**
