### PR TITLE
Set SAML Features To Computed (#655)

### LINKED ISSUE #655: Custom SAML App gets SCIM tab wiped out on re-apply on 3.13.10
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform version 0.13.5
provider version 3.13.10
### Affected Resource(s)

- okta_app_saml

### Terraform Configuration Files

```hcl
resource "okta_app_saml" "loom" {
  label                    = "Loom SAML"
  status                   = "ACTIVE"
  sso_url                  = "https://login.loom.com/login/callback"
  recipient                = "https://login.loom.com/login/callback"
  destination              = "https://login.loom.com/login/callback"
  audience                 = "redacted"
  subject_name_id_template = "$${user.userName}"
  subject_name_id_format   = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
  response_signed          = true
  assertion_signed         = true
  signature_algorithm      = "RSA_SHA256"
  digest_algorithm         = "SHA256"
  honor_force_authn        = true
  hide_ios                 = true
  hide_web                 = true
  authn_context_class_ref  = "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"

  attribute_statements {
    type      = "EXPRESSION"
    name      = "email"
    namespace = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
    values    = ["user.login"]
  }

  attribute_statements {
    type      = "EXPRESSION"
    name      = "firstName"
    namespace = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
    values    = ["user.firstName"]
  }

  attribute_statements {
    type      = "EXPRESSION"
    name      = "lastName"
    namespace = "urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified"
    values    = ["user.lastName"]
  }

  skip_users  = true
  skip_groups = false

  lifecycle { ignore_changes = [groups] }
}
```

### Expected Behavior

No change to provisioning tab on custom SAML app for new apply

### Actual Behavior

We added skip_users and skip_groups to the TF for this custom SAML app which had provisioning features enabled manually via UI (the provider docs note these are not configurable via API yet) - on apply, the provisioning radio button got reset from SCIM to *None* and it wiped out the configuration on the provisioning that we had setup manually.

### Steps to Reproduce

Configure custom SAML app via TF
Configure provisioning options via Okta UI
Make a change to custom SAML app via TF
Apply TF plan - TF apply will wipe out provisioning settings and reset the "Provisioning" option on the custom saml app to *None*

Note - We had originally seen this happen on 3.13.7 - we upgraded providers recently for another issue (to get the skip_users/groups attributes) and saw this pop up again. Let us know if we're missing something as far as what we should be setting on custom SAML apps with custom SCIM integrations!

### PR DESCRIPTION
**Pull request by ymylei**
Designed to help/fix #655 

What: `features` should be set as computed, which is the proper `ReadOnly` flag for a terraform attribute.

Setting this allowed me to run a terraform apply (changing the name of a test app that had the SAML config turned on), with the following results in the comments.

### CODE REVIEW

**Comment by ymylei** [comment]
```
PUT https://dev-385667.okta.com/api/v1/apps/0oa8w6bnbl6p8dqEa4x7 HTTP/2.0
authorization: SSWS <redacted>
user-agent: okta-sdk-golang/2.14.0 golang/go1.19 darwin/arm64 okta-terraform/3.35.0
accept: application/json
content-type: application/json
content-length: 1212
accept-encoding: gzip


{
    "accessibility": {
        "selfService": false
    },
    "credentials": {
        "signing": {
            "kid": "gPnq2icdE4W_qph46nmMwchXhcEnlgvb14Olfz2MDPU"
        },
        "userNameTemplate": {
            "template": "${source.login}",
            "type": "BUILT_IN"
        }
    },
    "label": "test1",
    "name": "dev-385667_test_3",
    "settings": {
        "app": {},
        "implicitAssignment": false,
        "notes": {
            "admin": null,
            "enduser": null
        },
        "signOn": {
            "allowMultipleAcsEndpoints": false,
            "assertionSigned": false,
            "attributeStatements": [],
            "audience": "https://example.com/audience",
            "audienceOverride": "",
            "authnContextClassRef": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
            "defaultRelayState": "",
            "destination": "https://example.com",
            "destinationOverride": "",
            "digestAlgorithm": "SHA256",
            "honorForceAuthn": false,
            "idpIssuer": "http://www.okta.com/${org.externalKey}",
            "recipient": "https://example.com",
            "recipientOverride": "",
            "responseSigned": true,
            "signatureAlgorithm": "RSA_SHA256",
            "slo": {
                "enabled": false
            },
            "ssoAcsUrl": "https://example.com",
            "ssoAcsUrlOverride": "",
            "subjectNameIdFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
            "subjectNameIdTemplate": "${user.userName}"
        }
    },
    "signOnMode": "SAML_2_0",
    "visibility": {
        "appLinks": {
            "dev-385667_test_3_link": true
        },
        "autoSubmitToolbar": false,
        "hide": {
            "iOS": false,
            "web": false
        }
    }
}
```

**Comment by ymylei** [comment]
```
TTP/2.0 200
date: Sun, 28 Aug 2022 06:02:33 GMT
content-type: application/json
server: nginx

{
    "_links": {
        "appLinks": [
            {
                "href": "https://dev-385667.okta.com/home/dev-385667_test_3/0oa8w6bnbl6p8dqEa4x7/aln8w6ibwlAKbu6Ls4x7",
                "name": "dev-385667_test_3_link",
                "type": "text/html"
            }
        ],
        "deactivate": {
            "href": "https://dev-385667.okta.com/api/v1/apps/0oa8w6bnbl6p8dqEa4x7/lifecycle/deactivate"
        },
        "groups": {
            "href": "https://dev-385667.okta.com/api/v1/apps/0oa8w6bnbl6p8dqEa4x7/groups"
        },
        "help": {
            "href": "https://dev-385667-admin.okta.com/app/dev-385667_test_3/0oa8w6bnbl6p8dqEa4x7/setup/help/SAML_2_0/instructions",
            "type": "text/html"
        },
        "logo": [
            {
                "href": "https://ok11static.oktacdn.com/assets/img/logos/default.6770228fb0dab49a1695ef440a5279bb.png",
                "name": "medium",
                "type": "image/png"
            }
        ],
        "metadata": {
            "href": "https://dev-385667.okta.com/api/v1/apps/0oa8w6bnbl6p8dqEa4x7/sso/saml/metadata",
            "type": "application/xml"
        },
        "uploadLogo": {
            "hints": {
                "allow": [
                    "POST"
                ]
            },
            "href": "https://dev-385667.okta.com/api/v1/apps/0oa8w6bnbl6p8dqEa4x7/logo"
        },
        "users": {
            "href": "https://dev-385667.okta.com/api/v1/apps/0oa8w6bnbl6p8dqEa4x7/users"
        }
    },
    "accessibility": {
        "errorRedirectUrl": null,
        "loginRedirectUrl": null,
        "selfService": false
    },
    "created": "2022-08-28T05:55:33.000Z",
    "credentials": {
        "signing": {
            "kid": "gPnq2icdE4W_qph46nmMwchXhcEnlgvb14Olfz2MDPU"
        },
        "userNameTemplate": {
            "template": "${source.login}",
            "type": "BUILT_IN"
        }
    },
    "features": [
        "SCIM_PROVISIONING"
    ],
    "id": "0oa8w6bnbl6p8dqEa4x7",
    "label": "test1",
    "lastUpdated": "2022-08-28T06:02:33.000Z",
    "name": "dev-385667_test_3",
    "settings": {
        "app": {},
        "notes": {
            "admin": null,
            "enduser": null
        },
        "notifications": {
            "vpn": {
                "helpUrl": null,
                "message": null,
                "network": {
                    "connection": "DISABLED"
                }
            }
        },
        "signOn": {
            "acsEndpoints": [],
            "allowMultipleAcsEndpoints": false,
            "assertionSigned": false,
            "attributeStatements": [],
            "audience": "https://example.com/audience",
            "authnContextClassRef": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
            "defaultRelayState": "",
            "destination": "https://example.com",
            "digestAlgorithm": "SHA256",
            "honorForceAuthn": false,
            "idpIssuer": "http://www.okta.com/${org.externalKey}",
            "inlineHooks": [],
            "recipient": "https://example.com",
            "requestCompressed": false,
            "responseSigned": true,
            "signatureAlgorithm": "RSA_SHA256",
            "slo": {
                "enabled": false
            },
            "spIssuer": null,
            "ssoAcsUrl": "https://example.com",
            "subjectNameIdFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
            "subjectNameIdTemplate": "${user.userName}"
        }
    },
    "signOnMode": "SAML_2_0",
    "status": "ACTIVE",
    "visibility": {
        "appLinks": {
            "dev-385667_test_3_link": true
        },
        "autoLaunch": false,
        "autoSubmitToolbar": false,
        "hide": {
            "iOS": false,
            "web": false
        }
    }
}
```

**Comment by monde** [comment]
ACK https://github.com/okta/terraform-provider-okta/pull/1273#issuecomment-1230566754

**Review by monde — COMMENTED** [review]
API docs on `features` property are imprecise.

- https://developer.okta.com/docs/reference/api/apps/#application-properties
- https://developer.okta.com/docs/reference/api/apps/#features

**Review by monde — COMMENTED** [review]
**OIE**

```
for t in `grep "func Test" okta/resource_okta_app_saml_test.go | awk '{ print $2}'| sed -e 's/(.*//g'`; do
TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^${t} ./okta
done
=== RUN   TestAccAppSaml_conditionalRequire
--- PASS: TestAccAppSaml_conditionalRequire (2.05s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    2.460s
=== RUN   TestAccAppSaml_invalidURL
--- PASS: TestAccAppSaml_invalidURL (0.17s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    0.420s
=== RUN   TestAccAppSaml_crud
--- PASS: TestAccAppSaml_crud (65.19s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    65.427s
=== RUN   TestAccAppSaml_preconfigured
--- PASS: TestAccAppSaml_preconfigured (11.31s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    11.651s
=== RUN   TestAccAppSaml_userGroups
--- PASS: TestAccAppSaml_userGroups (49.95s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    50.186s
=== RUN   TestAccAppSaml_inlineHook
--- PASS: TestAccAppSaml_inlineHook (9.38s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    9.687s
=== RUN   TestAccAppSaml_federationBroker
    resource_okta_app_saml_test.go:309: This is an 'Early Access Feature' and needs to be enabled by Okta, skipping this test as it fails when this feature is not available
--- SKIP: TestAccAppSaml_federationBroker (0.00s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    0.260s
=== RUN   TestAccResourceOktaAppSaml_timeouts
--- PASS: TestAccResourceOktaAppSaml_timeouts (8.25s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    8.531s
```

**Classic**
```
for t in `grep "func Test" okta/resource_okta_app_saml_test.go | awk '{ print $2}'| sed -e 's/(.*//g'`; do
  TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^${t} ./okta
done
=== RUN   TestAccAppSaml_conditionalRequire
--- PASS: TestAccAppSaml_conditionalRequire (1.98s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    2.237s
=== RUN   TestAccAppSaml_invalidURL
--- PASS: TestAccAppSaml_invalidURL (0.17s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    (cached)
=== RUN   TestAccAppSaml_crud
--- PASS: TestAccAppSaml_crud (67.10s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    67.340s
=== RUN   TestAccAppSaml_preconfigured
--- PASS: TestAccAppSaml_preconfigured (11.63s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    11.858s
=== RUN   TestAccAppSaml_userGroups
--- PASS: TestAccAppSaml_userGroups (49.92s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    50.157s
=== RUN   TestAccAppSaml_inlineHook
--- PASS: TestAccAppSaml_inlineHook (8.93s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    9.177s
=== RUN   TestAccAppSaml_federationBroker
    resource_okta_app_saml_test.go:309: This is an 'Early Access Feature' and needs to be enabled by Okta, skipping this test as it fails when this feature is not available
--- SKIP: TestAccAppSaml_federationBroker (0.00s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    (cached)
=== RUN   TestAccResourceOktaAppSaml_timeouts
--- PASS: TestAccResourceOktaAppSaml_timeouts (7.94s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    8.202s
```

**Review by monde — APPROVED** [review]
Thanks again for all your PRs @ymylei

**Pull request merged**
