### PR TITLE
Update Repository with latest Original

### PR DESCRIPTION
**Pull request by quantumew**
* Pull in all changes from github.com/articulate/terraform-provider-okta
* Remove Articulate allusions
* Pull in .github/ related docs from AWS and update to apply to this provider

### CODE REVIEW

**Comment by quantumew** [comment]
Screen Shot 2020-02-16 at 10 29 16 PM
Screen Shot 2020-02-16 at 10 29 29 PM
Screen Shot 2020-02-16 at 10 29 41 PM

**Review by cgriggs01 — APPROVED** [review]
LGTM, thanks for making this happen!

**Comment by cgriggs01** [comment]
When running the tests from my side, I am getting a number of errors. I assume its the credential that I was provided awhile back. We can move forward with the merge and release. And I'll work with ya'll to get the tests running in TeamCity

**Comment by quantumew** [comment]
@cgriggs01 remind me, what account do you run against? Feel free to post or email me your output if you get your API token refreshed. I don’t mind getting your account straightened out before moving forward.

**Comment by quantumew** [comment]
@cgriggs01 Per our email communication I will get this merged. Let me know if you run into any issues after updating your API token. One thing I ran into testing against my account was errors related to missing features. Let me know if you hit that, and we will work with Okta to get the account updated to support all of the features we are testing here.

**Comment by icebal** [comment]
running the newly released version is giving the below error during refresh. commenting out the okta resource makes the error go away. this is with a new api token

rpc error: code = Unavailable desc = transport is closing

**Comment by quantumew** [comment]
@icebal which resource is this happening on? Generally that RPC error is in the presence of other more informative errors. Is there any other error output? Alternatively, can you run the refresh with TF_LOG=debug?

**Comment by icebal** [comment]
there is no other log output, and will try with higher logs.

**Comment by icebal** [comment]
FYI, i am using this for work, so i'm unable to give all the info in a standard bug report.

**Comment by icebal** [comment]
here is the debug logs, the only error happens in the okta goroutine:
`2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: 
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: goroutine 21 [running]:
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: github.com/okta/okta-sdk-golang/okta.NewClient(0x13bd360, 0xc00003a0c8, 0xc0005fd8f0, 0x8, 0x8, 0x0, 0xc0004855c0, 0xc0001d4000)
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-okta/vendor/github.com/okta/okta-sdk-golang/okta/okta.go:89 +0x495
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: github.com/terraform-providers/terraform-provider-okta/okta.(*Config).loadAndValidate(0xc0001ce5b0, 0x111e047, 0x7)
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-okta/okta/config.go:61 +0x57a
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: github.com/terraform-providers/terraform-provider-okta/okta.providerConfigure(0xc0001ce540, 0x0, 0xc000483420, 0xc0001ce540, 0x0)
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-okta/okta/provider.go:220 +0x3d5
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Configure(0xc000547b00, 0xc00016a270, 0xf9ec00, 0xc00016a1e0)
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-okta/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:275 +0xf6
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).Configure(0xc0001382d0, 0x13bd3e0, 0xc00039b710, 0xc000484d00, 0xc0001382d0, 0xc00039b710, 0xc000247bd0)
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-okta/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:487 +0x2e6
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_Configure_Handler(0x10da800, 0xc0001382d0, 0x13bd3e0, 0xc00039b710, 0xc000120a80, 0x0, 0x13bd3e0, 0xc00039b710, 0xc0002fe6c0, 0x86)
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-okta/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3135 +0x23e
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003b0160, 0x13c9840, 0xc00010fe00, 0xc000164000, 0xc000375fb0, 0x1c2e1d8, 0x0, 0x0, 0x0)
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-okta/vendor/google.golang.org/grpc/server.go:995 +0x466
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc0003b0160, 0x13c9840, 0xc00010fe00, 0xc000164000, 0x0)
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-okta/vendor/google.golang.org/grpc/server.go:1275 +0xda6
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000496150, 0xc0003b0160, 0x13c9840, 0xc00010fe00, 0xc000164000)
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-okta/vendor/google.golang.org/grpc/server.go:710 +0x9f
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-02-19T21:47:06.278Z [DEBUG] plugin.terraform-provider-okta_v3.1.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-okta/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020-02-19T21:47:06.280Z [DEBUG] plugin: plugin process exited: path=/home/user/.terraform/plugins/linux_amd64/terraform-provider-okta_v3.1.0_x4 pid=290 error="exit status 2"
2020/02/19 21:47:06 [ERROR] <root>: eval: *terraform.EvalConfigProvider, err: rpc error: code = Canceled desc = context canceled
2020/02/19 21:47:06 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Canceled desc = context canceled
2020/02/19 21:47:06 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: rpc error: code = Canceled desc = context canceled
2020/02/19 21:47:06 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Canceled desc = context canceled`

**Comment by icebal** [comment]
FYI, this occurs even if i only have the required label parameter.

**Comment by quantumew** [comment]
@icebal Interesting. Definitely sounds like a bug. Would guess that we are missing a test case. Open an issue for you.

**Comment by quantumew** [comment]
@icebal Thanks for the output, that helped a lot. I looked at the debug output a bit closer. This appears to be a config related panic. I have never seen this code but apparently Okta's SDK does some validation and they panic if they find an issue rather then returning an error 🤦‍♂. I think this should be addressed either with a recovery on our end or a more sensible error on their side. Can you validate you are setting a valid API token and URI?

https://github.com/terraform-providers/terraform-provider-okta/blob/0c1611a960c7c7b35c14ca2edbf99649c970119a/vendor/github.com/okta/okta-sdk-golang/okta/validator.go#L8

**Comment by quantumew** [comment]
@icebal We can move any future talk over to #8. Thanks!

**Pull request merged**
