### PR TITLE
Add group target support for okta_group_role

### LINKED ISSUE #280: okta_group_roles resource is missing features to specify "all {apps|groups}" or "specific {apps|groups}"
(copied from #189 as it was marked stale erroneously)

### Community Note
* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The okta_group_roles resource (registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/group_roles) allows you to assign a group to admin permissions. Some of these admin permissions, e.g. Help Desk Administrator HELP_DESK_ADMIN, allow you to subsequently choose in the Okta GUI whether this means "Can administer all users" or "Can administer users in specific groups", and if you choose the latter you then specify the groups. This is similar for "Group Membership Admin Permissions", "Application Administrator", "Group Administrator".

With the terraform resource, you cannot indicate if you want to constrain the groups/apps the admin can manage (i.e. it defaults to "Can administer all users" and the alternative option is not possible).

This behaviour does appear possible with the Okta API directly developer.okta.com/docs/reference/api/roles/#add-group-target-to-group-administrator-role-given-to-a-group, it also explains the behaviour is incremental - i.e. "all apps/groups" by default, but then specify a app/group to scope the behaviour.

### PR DESCRIPTION
**Pull request by ymylei**
This adds additional schema to the `okta_group_role` resource and exposes the ability to assign a list of target groups to group admin role assignments which specifically support it.

**Important**: This relies upon / assumes #255 has been merged (it is appending schema to that resource created in the PR). You will find these commits in here temporarily until that is merged (or another similar resource is finished) in which case I will then rebase this and fix the test configurations based upon that outcome.

Combined with the PR mentioned above, this would replace #154.

### CODE REVIEW

**Comment by ymylei** [comment]
Would also appreciate any confirmation testing (acceptance testing) and other support on this one. The developer tenants do not have the ability (at least I'm not able to complete the acceptance tests and test the assignments in the UI) to do the fine grained administrator management things.

**Comment by ymylei** [comment]
Docs on the API have me in a bit of a bind here: https://developer.okta.com/docs/reference/api/roles/#remove-a-group-target-from-a-group-administrator-role-given-to-a-group

```
Note: Don't remove the last Group target from a role assignment, as this causes an exception. If you need a role assignment that applies to all Groups, the API consumer should delete the USER_ADMIN role assignment and recreate it.
```

Because of that, this may probably be better off being an embedded object inside of the `okta_group_role` resource instead of a standalone resource, since it cannot support delete operations fully without also affecting resource.

**Comment by ymylei** [comment]
Acceptance test results (would like some additional confirmations here):
```
tom@DESKTOP-NNSTVLT:~/terraform-provider-okta$ make testacc TEST=./okta TESTARGS='-run=TestAccOktaGroupAdminRole_crud'
go mod tidy
go mod vendor
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./okta -v -run=TestAccOktaGroupAdminRole_crud  -timeout 120m
=== RUN   TestAccOktaGroupAdminRole_crud
--- PASS: TestAccOktaGroupAdminRole_crud (19.63s)
PASS
ok      github.com/oktadeveloper/terraform-provider-okta/okta   19.637s
```

**Comment by bogdanprodan-okta** [comment]
Hi, @ymylei! Thanks for the PR! Everything looks good, I just have to double-check everything and I think this might be included in the upcoming 3.8.0 release.

**Comment by jlaundry** [comment]
@ymylei I admire your perseverance with this project, and I hope Okta reward you accordingly 😊

If I could make one suggestion/request, have you considered separating each target to be it's own resource, instead of a list? (i.e., like I did in #154)?

While I appreciate that this PR faithfully implements the Okta API structure, it isn't consistent with the Terraform principle that [resources should be a declarative representation of single component](https://www.terraform.io/docs/extend/hashicorp-provider-design-principles.html#resources-should-represent-a-single-api-object). The primary driver for this is that it makes it easier to implement modular config structure; we have cases were some group targets are not instantiated in a single Terraform repo, which will mean Terraform will remove those.

**Comment by ymylei** [comment]
> 
> 
> @ymylei I admire your perseverance with this project, and I hope Okta reward you accordingly 😊
> 
> If I could make one suggestion/request, have you considered separating each target to be it's own resource, instead of a list? (i.e., like I did in #154)?
> 
> While I appreciate that this PR faithfully implements the Okta API structure, it isn't consistent with the Terraform principle that [resources should be a declarative representation of single component](https://www.terraform.io/docs/extend/hashicorp-provider-design-principles.html#resources-should-represent-a-single-api-object). The primary driver for this is that it makes it easier to implement modular config structure; we have cases were some group targets are not instantiated in a single Terraform repo, which will mean Terraform will remove those.

Hey @jlaundry, 

Appreciate the kind comment!

Per the comment I made here: https://github.com/oktadeveloper/terraform-provider-okta/pull/256#issuecomment-750754003 and the pertinent line from the Okta API docs:
```
Note: Don't remove the last Group target from a role assignment, as this causes an exception. If you need a role assignment that applies to all Groups, the API consumer should delete the USER_ADMIN role assignment and recreate it.
```

The standalone resource would be unable to fully support delete operations since a full delete would require also require affecting the parent role resource itself, therefore I do not consider it a good candidate to exist by itself.

**Comment by ymylei** [comment]
To add to the above, if you take this branch, go to the commit https://github.com/oktadeveloper/terraform-provider-okta/pull/256/commits/d6de84cc6074537cc9ad98b0fcf712190bfd94fc and run the acceptance tests, you'll get the `exception` / api failure described above.

**Comment by bogdanprodan-okta** [comment]
Hi, @ymylei! I've merged your previous PR, so please fix the conflicts in this one! Thanks!

**Comment by ymylei** [comment]
@bogdanprodan-okta Just completed the rebase, updated acceptance test result below:
```
tom@DESKTOP-NNSTVLT:~/terraform-provider-okta$ make testacc TEST=./okta TESTARGS='-run=TestAccOktaGroupAdminRole_crud'
go mod tidy
go mod vendor
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./okta -v -run=TestAccOktaGroupAdminRole_crud  -timeout 120m
=== RUN   TestAccOktaGroupAdminRole_crud
--- PASS: TestAccOktaGroupAdminRole_crud (20.05s)
PASS
ok      github.com/oktadeveloper/terraform-provider-okta/okta   20.058s
```

**Pull request merged**
