### PR TITLE
Okta Group Schema Null Handling

### PR DESCRIPTION
**Pull request by ymylei**
What:
- In JSON, `null` is a valid values to have on a key. See: https://www.json.org/json-en.html
- In the Okta profiles (and API), `null` is equivalent to "unset"

This change adds some normalisation to the handling of the custom group profile objects (since the main profile objects, `name` and `description` are required), where values that are explicitly set as `null` are excluded/treated as unset.

Why:
- Due to the above JSON schema definition and Okta's API handling; someone who has passed `null` into a custom group profile attribute will get an unexpected diff between what terraform/json expects, a key set with a value of `null`, while Okta is returning the value as unset. This PR teaches terraform to treat those values as "unset" and makes it consistent with the Okta API.

### CODE REVIEW

**Comment by ymylei** [comment]
`commit 478fbcf1d50f7fd2110725ceda8665b735ee4a59 (HEAD -> schema-diff-null, origin/schema-diff-null)`
```
➜  terraform-provider-okta git:(schema-diff-null) TEST_FILTER="TestAccOktaGroup" make testacc 
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -run TestAccOktaGroup -timeout 120m
?       github.com/okta/terraform-provider-okta [no test files]
=== RUN   TestAccOktaGroupSchema_crud
2022/08/27 10:35:51 [ERROR] the API returned an error: Api validation failed: updateGroupSchemas. Causes: errorSummary: You cannot add the attribute with the variable name 'testAcc_2526016890977024846' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again.
2022/08/27 10:35:53 [ERROR] the API returned an error: Api validation failed: updateGroupSchemas. Causes: errorSummary: You cannot add the attribute with the variable name 'testAcc_2526016890977024846' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again.
2022/08/27 10:35:54 [ERROR] the API returned an error: Api validation failed: updateGroupSchemas. Causes: errorSummary: You cannot add the attribute with the variable name 'testAcc_2526016890977024846' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again.
2022/08/27 10:35:56 [ERROR] the API returned an error: Api validation failed: updateGroupSchemas. Causes: errorSummary: You cannot add the attribute with the variable name 'testAcc_2526016890977024846' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again.
2022/08/27 10:36:00 [ERROR] the API returned an error: Api validation failed: updateGroupSchemas. Causes: errorSummary: You cannot add the attribute with the variable name 'testAcc_2526016890977024846' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again.
2022/08/27 10:36:07 [ERROR] the API returned an error: Api validation failed: updateGroupSchemas. Causes: errorSummary: You cannot add the attribute with the variable name 'testAcc_2526016890977024846' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again.
2022/08/27 10:36:11 [ERROR] the API returned an error: Api validation failed: updateGroupSchemas. Causes: errorSummary: You cannot add the attribute with the variable name 'testAcc_2526016890977024846' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again.
2022/08/27 10:36:24 [ERROR] the API returned an error: Api validation failed: updateGroupSchemas. Causes: errorSummary: You cannot add the attribute with the variable name 'testAcc_2526016890977024846' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again.
2022/08/27 10:36:36 [ERROR] the API returned an error: Api validation failed: updateGroupSchemas. Causes: errorSummary: You cannot add the attribute with the variable name 'testAcc_2526016890977024846' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again.
2022/08/27 10:36:57 [ERROR] the API returned an error: Api validation failed: updateGroupSchemas. Causes: errorSummary: You cannot add the attribute with the variable name 'testAcc_2526016890977024846' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again.
2022/08/27 10:37:24 [ERROR] the API returned an error: Api validation failed: updateGroupSchemas. Causes: errorSummary: You cannot add the attribute with the variable name 'testAcc_2526016890977024846' because the deletion process for an attribute with the same variable name is incomplete. Wait until the data clean up process finishes and then try again.
--- PASS: TestAccOktaGroupSchema_crud (98.84s)
=== RUN   TestAccOktaGroupSchema_arrayString
--- PASS: TestAccOktaGroupSchema_arrayString (7.91s)
=== RUN   TestAccOktaGroupMembership_crud
--- PASS: TestAccOktaGroupMembership_crud (9.18s)
=== RUN   TestAccOktaGroupMembershipsIssue1119
    resource_okta_group_memberships_test.go:301: "OKTA_ALLOW_LONG_RUNNING_ACC_TEST" not present, skipping test
--- SKIP: TestAccOktaGroupMembershipsIssue1119 (0.01s)
=== RUN   TestAccOktaGroupAdminRole_crud
--- PASS: TestAccOktaGroupAdminRole_crud (15.17s)
=== RUN   TestAccOktaGroupAdminRoles_crud
--- PASS: TestAccOktaGroupAdminRoles_crud (8.64s)
=== RUN   TestAccOktaGroupRule_crud
--- PASS: TestAccOktaGroupRule_crud (13.74s)
=== RUN   TestAccOktaGroupRule_invalidHandle
--- PASS: TestAccOktaGroupRule_invalidHandle (11.16s)
=== RUN   TestAccOktaGroup_crud
=== PAUSE TestAccOktaGroup_crud
=== RUN   TestAccOktaGroup_customschema
=== PAUSE TestAccOktaGroup_customschema
=== RUN   TestAccOktaGroup_customschema_null
=== PAUSE TestAccOktaGroup_customschema_null
=== CONT  TestAccOktaGroup_crud
=== CONT  TestAccOktaGroup_customschema_null
=== CONT  TestAccOktaGroup_customschema
2022/08/27 10:38:31 [ERROR] failed to apply changes after several retries
2022/08/27 10:38:31 [ERROR] failed to apply changes after several retries
2022/08/27 10:38:31 [ERROR] failed to apply changes after several retries
2022/08/27 10:38:39 [ERROR] failed to apply changes after several retries
--- PASS: TestAccOktaGroup_customschema (10.22s)
--- PASS: TestAccOktaGroup_crud (10.40s)
2022/08/27 10:38:41 [ERROR] failed to apply changes after several retries
--- PASS: TestAccOktaGroup_customschema_null (12.44s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    177.325s
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/apimutex  (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/mutexkv   (cached) [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/okta/terraform-provider-okta/okta/internal/transport (cached) [no tests to run]
?       github.com/okta/terraform-provider-okta/sdk     [no test files]
```

**Comment by monde** [comment]
ACK https://github.com/okta/terraform-provider-okta/pull/1273#issuecomment-1230566754

**Review by monde — COMMENTED** [review]
**OIE**

```
for t in `grep "func Test" okta/resource_okta_group_test.go | awk '{ print $2}'| sed -e 's/(.*//g'`; do
  TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^${t} ./okta
done
=== RUN   TestAccOktaGroup_crud
=== PAUSE TestAccOktaGroup_crud
=== CONT  TestAccOktaGroup_crud
--- PASS: TestAccOktaGroup_crud (21.49s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    21.745s
=== RUN   TestAccOktaGroup_customschema
=== PAUSE TestAccOktaGroup_customschema
=== RUN   TestAccOktaGroup_customschema_null
=== PAUSE TestAccOktaGroup_customschema_null
=== CONT  TestAccOktaGroup_customschema
=== CONT  TestAccOktaGroup_customschema_null
2022/09/12 02:22:00 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:00 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:00 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:00 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:02 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:16 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:17 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:17 [ERROR] failed to apply changes after several retries
--- PASS: TestAccOktaGroup_customschema (20.29s)
--- PASS: TestAccOktaGroup_customschema_null (20.64s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    20.887s
=== RUN   TestAccOktaGroup_customschema_null
=== PAUSE TestAccOktaGroup_customschema_null
=== CONT  TestAccOktaGroup_customschema_null
2022/09/12 02:22:24 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:24 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:41 [ERROR] failed to apply changes after several retries
--- PASS: TestAccOktaGroup_customschema_null (21.41s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    21.684s
```

**Classic**

```
for t in `grep "func Test" okta/resource_okta_group_test.go | awk '{ print $2}'| sed -e 's/(.*//g'`; do
TF_ACC=1 go test -tags unit -mod=readonly -test.v -run ^${t} ./okta
done
=== RUN   TestAccOktaGroup_crud
=== PAUSE TestAccOktaGroup_crud
=== CONT  TestAccOktaGroup_crud
--- PASS: TestAccOktaGroup_crud (17.73s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    18.168s
=== RUN   TestAccOktaGroup_customschema
=== PAUSE TestAccOktaGroup_customschema
=== RUN   TestAccOktaGroup_customschema_null
=== PAUSE TestAccOktaGroup_customschema_null
=== CONT  TestAccOktaGroup_customschema
=== CONT  TestAccOktaGroup_customschema_null
2022/09/12 02:21:47 [ERROR] failed to apply changes after several retries
2022/09/12 02:21:47 [ERROR] failed to apply changes after several retries
2022/09/12 02:21:47 [ERROR] failed to apply changes after several retries
2022/09/12 02:21:47 [ERROR] failed to apply changes after several retries
2022/09/12 02:21:47 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:01 [ERROR] failed to apply changes after several retries
--- PASS: TestAccOktaGroup_customschema (17.96s)
2022/09/12 02:22:04 [ERROR] failed to apply changes after several retries
--- PASS: TestAccOktaGroup_customschema_null (19.91s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    20.147s
=== RUN   TestAccOktaGroup_customschema_null
=== PAUSE TestAccOktaGroup_customschema_null
=== CONT  TestAccOktaGroup_customschema_null
2022/09/12 02:22:08 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:08 [ERROR] failed to apply changes after several retries
2022/09/12 02:22:25 [ERROR] failed to apply changes after several retries
--- PASS: TestAccOktaGroup_customschema_null (20.69s)
PASS
ok      github.com/okta/terraform-provider-okta/okta    20.951s
```

**Review by monde — APPROVED** [review]
Excellent PR @ymylei

**Pull request merged**
